# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZaCLvZbq75NvRtMNFhEObTv61NdX3QrT
"""

import tensorflow as tf
import numpy as np

celsius = np.array([-40,-10,0,8,15,22,38], dtype=float)
farenheit = np.array([-40,14,32,46,59,72,100], dtype=float)

capa = tf.keras.layers.Dense(units=1, input_shape=[1])
modelo = tf.keras.Sequential([capa])

modelo.compile(
    optimizer=tf.keras.optimizers.Adam(0.1),
    loss='mean_squared_error'
)

print('トレーニングスタート...')
historial = modelo.fit(celsius,farenheit, epochs=1000, verbose=False)
print('トレーニング終了！')

import matplotlib.pyplot as plt
plt.xlabel("#epoca")
plt.xlabel("error")
plt.plot(historial.history["loss"])

print("要則をしましょう")
resultado=modelo.predict([100.0])
print("結果は " +str(resultado)+" 華氏です! ")